#cloud-config
runcmd:
  - sudo apt-get install ntp
  - sudo service ntp stop
  - sudo ntpd -gq
  - sudo service ntp start
  - sudo apt-get update
  - sudo apt-get install git
  - sudo docker run -p 8080:8080 -t webgoat/webgoat-8.0
  - sudo docker run --rm -it -p 20:20 -p 21:21 -p 80:80 -p 443:443 -p 4848:4848 -p 6000:6000 -p 6060:6060 -p 7000:7000 -p 7181:7181 -p 7547:7547 -p 8000:8000 -p 8008:8008 -p 8020:8020 -p 8081:8080 -p 8400:8400 vulnerables/metasploit-vulnerability-emulator
  - docker run --rm -it -p 81:80 cyrivs89/web-dvws
  - docker run --rm -p 3000:3000 bkimminich/juice-shop